### ISSUE TITLE
tensorflow keras

### ISSUE THREAD

**Issue by benman1** [BenWhetton/keras-surgeon#29]
This looks really useful - thanks for working on this and making it available. I am just wondering about whether you plan to upgrade to tensorflow's keras sometime. I don't think the core keras is being updated that fast anymore.

**Comment by TianLin0509** [comment]
I think it's enough and can be successfully run with tensorflow2.0.
The only main problem is that some layers are not supported.

**Comment by Raukk** [comment]
Hey @benman1,
I just wanted to tell you that I have Forked this project to create a Version that works with TensorFlow.Keras.

You can find it here:
https://github.com/Raukk/tf-keras-surgeon

Thanks

**Comment by benman1** [comment]
Thanks! I'll give it a go.

**Comment by BenWhetton** [comment]
I'm taking a bit of time to address some of the issues that have built up over time on this project and I think this is probably the most important.

Standalone Keras no longer supports any backends except tensorflow. In fact, it depends on tensorflow and imports pretty much all of its functionality from `tf.keras`. This makes it really easy to support both now.
Keras-surgeon will depend on tf.keras and my initial testing shows that this will make it work with standalone Keras models as well.

I'm going to drop support for Tensorflow 1 since there were some major changes to the API and it would be a real mess to keep backwards compatibility. It's been about a year since TF2 was released now so I hope this won't be a big problem for most users.

@Raukk thanks for making a tf.keras compatible version available to the community. I'm sorry I was unresponsive to your input here for so long. I've had a look at your pull request but something seems to have gone wrong since there's no content in it anymore. I see there are a few breaking issues on your fork as well. They will be resolved when I push the changes I'm working on.

**Comment by BenWhetton** [comment]
Solved in 0.2.0
