### ISSUE TITLE
find_nodes_in_model in utils.py will only append 0

### ISSUE THREAD

**Issue by ShrutheeshIR** [BenWhetton/keras-surgeon#32]
find_nodes_in_model in utils append 'i' and not  the index of the node. Please explain this specific part as i will always be 0

**Comment by BenWhetton** [comment]
That method isn't really part of the library's public API. The same applies to quite a few methods in `utils.py`. I didn't structure this clearly. I'll try to clean it up at some point soon.

To answer your question. In this code:
```python3
 for i, node in enumerate(get_inbound_nodes(layer)):
        if node in model_nodes:
            node_indices.append(i)
```
`enumerate` iterates over the inbound nodes of the layer. `i` is the index and `node` is the node so `i` won't always be 0.
I hope that helps.

I'm going to close this since I don't think there's an issue here.
